apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: community-session-demo
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joeporpeglia
spec:
  profile:
    displayName: Joe Porpeglia
  memberOf: [team-a]
